services:
  #
  # NATS cluster node1 section
  #
  nats_n1:
    image: nats:latest
    container_name: nats_n1
    restart: on-failure
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./volume/nats/nats_n1:/data
    networks:
      - bsp_net
    environment:
      - NATS_CLUSTER_ADVERTISE=nats_n1:6222
      - NATS_SERVER_NAME=nats_n1
      - NATS_LISTEN_CLIENTS=0.0.0.0
      - NATS_LISTEN_CLUSTER=0.0.0.0
      - NATS_ROUTE_PORT=6222
      - NATS_JETSTREAM=true
      - NATS_JETSTREAM_DIR=./volume/nats/jetstream
    command: ["-js"]
    healthcheck:
      test: ["CMD", "nats_server", "--signal", "healthz"]
      interval: 5s
      retries: 5
      timeout: 2s
  #
  # NATS cluster node2 section
  #
  nats_n2:
    image: nats:latest
    container_name: nats_n2
    restart: on-failure
    ports:
      - "4223:4222"
      - "8223:8222"
    volumes:
      - ./volume/nats/nats_n2:/data
    networks:
      - bsp_net
    environment:
      - NATS_CLUSTER_ADVERTISE=nats_n2:6222
      - NATS_SERVER_NAME=nats_n2
      - NATS_LISTEN_CLIENTS=0.0.0.0
      - NATS_LISTEN_CLUSTER=0.0.0.0
      - NATS_ROUTE_PORT=6222
      - NATS_JETSTREAM=true
      - NATS_JETSTREAM_DIR=./volume/nats/jetstream
    command: ["-js"]
    healthcheck:
      test: ["CMD", "nats_server", "--signal", "healthz"]
      interval: 5s
      retries: 5
      timeout: 2s
    depends_on:
      - nats_n1
  #
  # NATS cluster node3 section
  #
  nats_n3:
    image: nats:latest
    container_name: nats_n3
    restart: on-failure
    ports:
      - "4224:4222"
      - "8224:8222"
    volumes:
      - ./volume/nats/nats_n3:/data
    networks:
      - bsp_net
    environment:
      - NATS_CLUSTER_ADVERTISE=nats_n3:6222
      - NATS_SERVER_NAME=nats_n3
      - NATS_LISTEN_CLIENTS=0.0.0.0
      - NATS_LISTEN_CLUSTER=0.0.0.0
      - NATS_ROUTE_PORT=6222
      - NATS_JETSTREAM=true
      - NATS_JETSTREAM_DIR=./volume/nats/jetstream
    command: ["-js"]
    healthcheck:
      test: ["CMD", "nats_server", "--signal", "healthz"]
      interval: 5s
      retries: 5
      timeout: 2s
    depends_on:
      - nats_n1
  #
  # Postgres section
  #
  postgres:
    image: postgres:17
    container_name: postgres
    restart: on-failure
    # env_file:
    #   - .env
    networks:
      - bsp_net
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "system", "-d", "bspdb_dev"]
      interval: 5s
      retries: 5
      timeout: 2s
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
  #
  # Redis section
  #
  redis:
    image: redis:7.4
    container_name: redis
    restart: on-failure
    networks:
      - bsp_net
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      timeout: 2s
    volumes:
      - ./volume/redis:/data
  #
  # Api section
  #
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: brickwall:0.1.0
    container_name: api
    restart: on-failure
    command: "/app/bsp api"
    networks:
      - bsp_net
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      # nats:
      #   condition: service_healthy
      redis:
        condition: service_healthy
  #
  # Smtp section
  #
  smtp:
    image: brickwall:0.1.0
    container_name: smtp
    restart: on-failure
    command: "/app/bsp smtp"
    networks:
      - bsp_net
    ports:
      - "8082:8081"
  #
  # Auth section
  #
  auth:
    image: brickwall:0.1.0
    container_name: auth
    restart: on-failure
    command: "/app/bsp auth"
    networks:
      - bsp_net
    ports:
      - "8083:8081"
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    #   # nats:
    #   #   condition: service_healthy
    #   redis:
    #     condition: service_healthy
#
# Networks section
#
networks:
  bsp_net:
    name: bsp_net
    driver: bridge
#
# eof
#
