services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    env_file:
      - .env
    networks:
      - bsp_net
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "system", "-d", "bspdb_dev"]
      interval: 5s
      retries: 5
      timeout: 2s
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
  nats:
    image: nats:2.11
    container_name: nats
    restart: always
    env_file:
      - .env
    networks:
      - bsp_net
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js"]
    healthcheck:
      test: ["CMD", "nats-server", "--signal", "healthz"]
      interval: 5s
      retries: 5
      timeout: 2s
    volumes:
      - ./volume/nats:/nats
  redis:
    image: redis:7.4
    container_name: redis
    restart: always
    env_file:
      - .env
    networks:
      - bsp_net
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      timeout: 2s
    volumes:
      - ./volume/redis:/data
  maildev:
    image: maildev/maildev
    container_name: maildev
    restart: always
    env_file:
      - .env
    networks:
      - bsp_net
    ports:
      - "1080:1080" # Web
      - "1025:1025" # SMTP server
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://maildev:1080"]
      interval: 5s
      retries: 5
      timeout: 3s
  api:
    build: .
    container_name: api
    restart: always
    env_file:
      - .env
    networks:
      - bsp_net
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      # nats:
      #   condition: service_healthy
      redis:
        condition: service_healthy
      maildev:
        condition: service_healthy

networks:
  bsp_net:
    driver: bridge
#
# eof
#
