// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: contact.sql

package dbs

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const contactCount = `-- name: ContactCount :one
select count(*) from contact
`

// ContactCount
//
//	select count(*) from contact
func (q *Queries) ContactCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, contactCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contactCountByUserID = `-- name: ContactCountByUserID :one
select count(*) from contact where user_id = $1
`

// ContactCountByUserID
//
//	select count(*) from contact where user_id = $1
func (q *Queries) ContactCountByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, contactCountByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contactDeleteByID = `-- name: ContactDeleteByID :one
delete from contact c where c.id = $1 returning id
`

// ContactDeleteByID
//
//	delete from contact c where c.id = $1 returning id
func (q *Queries) ContactDeleteByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, contactDeleteByID, id)
	err := row.Scan(&id)
	return id, err
}

const contactNew = `-- name: ContactNew :one
insert into Contact(
    user_id, class, content
) values(
    $1, $2, $3
) returning id, user_id, class, content, created_at, updated_at
`

type ContactNewParams struct {
	UserID  string `json:"user_id"`
	Class   string `json:"class"`
	Content string `json:"content"`
}

// ContactNew
//
//	insert into Contact(
//	    user_id, class, content
//	) values(
//	    $1, $2, $3
//	) returning id, user_id, class, content, created_at, updated_at
func (q *Queries) ContactNew(ctx context.Context, arg *ContactNewParams) (*Contact, error) {
	row := q.db.QueryRow(ctx, contactNew, arg.UserID, arg.Class, arg.Content)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Class,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const contactSelect = `-- name: ContactSelect :many
select id, user_id, class, content, created_at, updated_at
  from contact
 order by $1::text
 limit $3 offset $2
`

type ContactSelectParams struct {
	SqlOrder  string `json:"sql_order"`
	SqlOffset int32  `json:"sql_offset"`
	SqlLimit  int32  `json:"sql_limit"`
}

// ContactSelect
//
//	select id, user_id, class, content, created_at, updated_at
//	  from contact
//	 order by $1::text
//	 limit $3 offset $2
func (q *Queries) ContactSelect(ctx context.Context, arg *ContactSelectParams) ([]*Contact, error) {
	rows, err := q.db.Query(ctx, contactSelect, arg.SqlOrder, arg.SqlOffset, arg.SqlLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Class,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contactSelectByID = `-- name: ContactSelectByID :one
select id, user_id, class, content, created_at, updated_at from contact c where c.id = $1
`

// ContactSelectByID
//
//	select id, user_id, class, content, created_at, updated_at from contact c where c.id = $1
func (q *Queries) ContactSelectByID(ctx context.Context, id string) (*Contact, error) {
	row := q.db.QueryRow(ctx, contactSelectByID, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Class,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const contactSelectByUserID = `-- name: ContactSelectByUserID :many
select id, user_id, class, content, created_at, updated_at from contact c where c.user_id = $1 order by c.class
`

// ContactSelectByUserID
//
//	select id, user_id, class, content, created_at, updated_at from contact c where c.user_id = $1 order by c.class
func (q *Queries) ContactSelectByUserID(ctx context.Context, userID string) ([]*Contact, error) {
	rows, err := q.db.Query(ctx, contactSelectByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Class,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contactSelectByUserIDClass = `-- name: ContactSelectByUserIDClass :many
select id, user_id, class, content, created_at, updated_at from contact c
 where c.user_id = $1
   and c.class = $2
   and c.content = $3
`

type ContactSelectByUserIDClassParams struct {
	UserID  string `json:"user_id"`
	Class   string `json:"class"`
	Content string `json:"content"`
}

// ContactSelectByUserIDClass
//
//	select id, user_id, class, content, created_at, updated_at from contact c
//	 where c.user_id = $1
//	   and c.class = $2
//	   and c.content = $3
func (q *Queries) ContactSelectByUserIDClass(ctx context.Context, arg *ContactSelectByUserIDClassParams) ([]*Contact, error) {
	rows, err := q.db.Query(ctx, contactSelectByUserIDClass, arg.UserID, arg.Class, arg.Content)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Class,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contactSelectUserByClass = `-- name: ContactSelectUserByClass :one
select u.id, c.content as email, u.username, u.is_blocked, u.blocked_at, u.is_checked, u.checked_at, u.visited_at, u.created_at
  from users u
  join contact c on u.id = c.user_id
where c.class = $1
  and c.content = $2
`

type ContactSelectUserByClassParams struct {
	Class   string `json:"class"`
	Content string `json:"content"`
}

type ContactSelectUserByClassRow struct {
	ID        string           `json:"id"`
	Email     string           `json:"email"`
	Username  string           `json:"username"`
	IsBlocked bool             `json:"is_blocked"`
	BlockedAt pgtype.Timestamp `json:"blocked_at"`
	IsChecked bool             `json:"is_checked"`
	CheckedAt pgtype.Timestamp `json:"checked_at"`
	VisitedAt pgtype.Timestamp `json:"visited_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

// ContactSelectUserByClass
//
//	select u.id, c.content as email, u.username, u.is_blocked, u.blocked_at, u.is_checked, u.checked_at, u.visited_at, u.created_at
//	  from users u
//	  join contact c on u.id = c.user_id
//	where c.class = $1
//	  and c.content = $2
func (q *Queries) ContactSelectUserByClass(ctx context.Context, arg *ContactSelectUserByClassParams) (*ContactSelectUserByClassRow, error) {
	row := q.db.QueryRow(ctx, contactSelectUserByClass, arg.Class, arg.Content)
	var i ContactSelectUserByClassRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.IsChecked,
		&i.CheckedAt,
		&i.VisitedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const contactUpdateByID = `-- name: ContactUpdateByID :one
update contact
   set class = $1, content = $2
 where id = $3 returning id, user_id, class, content, created_at, updated_at
`

type ContactUpdateByIDParams struct {
	Class   string `json:"class"`
	Content string `json:"content"`
	ID      string `json:"id"`
}

// ContactUpdateByID
//
//	update contact
//	   set class = $1, content = $2
//	 where id = $3 returning id, user_id, class, content, created_at, updated_at
func (q *Queries) ContactUpdateByID(ctx context.Context, arg *ContactUpdateByIDParams) (*Contact, error) {
	row := q.db.QueryRow(ctx, contactUpdateByID, arg.Class, arg.Content, arg.ID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Class,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
