// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbs

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contact struct {
	ID        string           `json:"id"`
	UserID    string           `json:"user_id"`
	Class     string           `json:"class"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Country struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Iso2      string           `json:"iso2"`
	Iso3      string           `json:"iso3"`
	NumCode   int16            `json:"num_code"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type CountryCurrency struct {
	ID         string           `json:"id"`
	CountryID  string           `json:"country_id"`
	CurrencyID string           `json:"currency_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Currency struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Code      string           `json:"code"`
	NumCode   int16            `json:"num_code"`
	Symbol    string           `json:"symbol"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Profile struct {
	ID        string           `json:"id"`
	UserID    string           `json:"user_id"`
	Firstname string           `json:"firstname"`
	Lastname  string           `json:"lastname"`
	Gender    string           `json:"gender"`
	Birthday  pgtype.Date      `json:"birthday"`
	AvatarUrl string           `json:"avatar_url"`
	Enable2fa bool             `json:"enable_2fa"`
	Secret2fa pgtype.Text      `json:"secret_2fa"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Role struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID        string           `json:"id"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
	IsBlocked bool             `json:"is_blocked"`
	BlockedAt pgtype.Timestamp `json:"blocked_at"`
	IsChecked bool             `json:"is_checked"`
	CheckedAt pgtype.Timestamp `json:"checked_at"`
	VisitedAt pgtype.Timestamp `json:"visited_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type VUserProfile struct {
	UserID           string      `json:"user_id"`
	ProfileID        pgtype.Text `json:"profile_id"`
	UserUsername     string      `json:"user_username"`
	UserIsBlocked    bool        `json:"user_is_blocked"`
	UserIsChecked    bool        `json:"user_is_checked"`
	ProfileFirstname pgtype.Text `json:"profile_firstname"`
	ProfileLastname  pgtype.Text `json:"profile_lastname"`
	ProfileGender    pgtype.Text `json:"profile_gender"`
	ProfileBirthday  pgtype.Date `json:"profile_birthday"`
	ProfileAvatarUrl pgtype.Text `json:"profile_avatar_url"`
	ProfileEnable2fa pgtype.Bool `json:"profile_enable_2fa"`
	ProfileSecret2fa pgtype.Text `json:"profile_secret_2fa"`
}
