@proto = http
@hostname = localhost:8081
@basepath = /api/v1/role
@baseurl = {{proto}}://{{hostname}}{{basepath}}
@contentType = application/json

### RoleSelect
@page = 1
@size = 10
@order = name
GET {{baseurl}}?page={{page}}&size={{size}}&order={{order}} HTTP/1.1
Content-Type: {{contentType}}
