--
-- Entity country
--
create table country (
    id          varchar(32)     not null default xid() primary key,
    name        varchar(255)    not null unique,
    iso2        char(2)         not null unique, -- ISO 3166-1 Alpha-2
    iso3        char(3)         not null unique, -- ISO 3166-1 Alpha-3
    num_code    smallint        not null unique, -- ISO 3166-1 Numeric
    created_at  timestamp       not null default timezone('utc', now()),
    updated_at  timestamp       not null default '1000-01-01'::timestamp
);

create trigger country_updated_at
	before update on country for each row
	execute procedure trigger_updated_at();
--
-- Entity currency
--
create table currency (
    id          varchar(32)     not null default xid() primary key,
    name        varchar(255)    not null unique,
    code        char(3)         not null unique,
    num_code    smallint        not null unique,
    symbol      varchar(8)      not null default '-',
    created_at  timestamp       not null default timezone('utc', now()),
    updated_at  timestamp       not null default '1000-01-01'::timestamp
);

create trigger currency_updated_at
	before update on currency for each row
	execute procedure trigger_updated_at();
--
-- Entity country_currency
--
create table country_currency (
    id          varchar(32)     not null default xid() primary key,
    country_id  varchar(32)     not null references country(id) on delete cascade,
    currency_id varchar(32)     not null references currency(id) on delete cascade,
    created_at  timestamp       not null default timezone('utc', now()),
    updated_at  timestamp       not null default '1000-01-01'::timestamp
);

create unique index country_currency_unq on country_currency(country_id, currency_id);

create trigger country_currency_updated_at
	before update on country_currency for each row
	execute procedure trigger_updated_at();
--
-- Country default data
--
insert into country(
    name, iso2, iso3, num_code
) values
  ('Afghanistan', 'AF', 'AFG', 4),
  ('Åland Islands', 'AX', 'ALA', 248),
  ('Albania', 'AL', 'ALB', 8),
  ('Algeria', 'DZ', 'DZA', 12),
  ('American Samoa', 'AS', 'ASM', 16),
  ('Andorra', 'AD', 'AND', 20),
  ('Angola', 'AO', 'AGO', 24),
  ('Anguilla', 'AI', 'AIA', 660),
  ('Antarctica', 'AQ', 'ATA', 10),
  ('Antigua and Barbuda', 'AG', 'ATG', 28),
  ('Argentina', 'AR', 'ARG', 32),
  ('Armenia', 'AM', 'ARM', 51),
  ('Aruba', 'AW', 'ABW', 533),
  ('Australia', 'AU', 'AUS', 36),
  ('Austria', 'AT', 'AUT', 40),
  ('Azerbaijan', 'AZ', 'AZE', 31),
  ('Bahamas', 'BS', 'BHS', 44),
  ('Bahrain', 'BH', 'BHR', 48),
  ('Bangladesh', 'BD', 'BGD', 50),
  ('Barbados', 'BB', 'BRB', 52),
  ('Belarus', 'BY', 'BLR', 112),
  ('Belgium', 'BE', 'BEL', 56),
  ('Belize', 'BZ', 'BLZ', 84),
  ('Benin', 'BJ', 'BEN', 204),
  ('Bermuda', 'BM', 'BMU', 60),
  ('Bhutan', 'BT', 'BTN', 64),
  ('Bolivia, Plurinational State of', 'BO', 'BOL', 68),
  ('Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', 535),
  ('Bosnia and Herzegovina', 'BA', 'BIH', 70),
  ('Botswana', 'BW', 'BWA', 72),
  ('Bouvet Island', 'BV', 'BVT', 74),
  ('Brazil', 'BR', 'BRA', 76),
  ('British Indian Ocean Territory', 'IO', 'IOT', 86),
  ('Brunei Darussalam', 'BN', 'BRN', 96),
  ('Bulgaria', 'BG', 'BGR', 100),
  ('Burkina Faso', 'BF', 'BFA', 854),
  ('Burundi', 'BI', 'BDI', 108),
  ('Cabo Verde', 'CV', 'CPV', 132),
  ('Cambodia', 'KH', 'KHM', 116),
  ('Cameroon', 'CM', 'CMR', 120),
  ('Canada', 'CA', 'CAN', 124),
  ('Cayman Islands', 'KY', 'CYM', 136),
  ('Central African Republic', 'CF', 'CAF', 140),
  ('Chad', 'TD', 'TCD', 148),
  ('Chile', 'CL', 'CHL', 152),
  ('China', 'CN', 'CHN', 156),
  ('Christmas Island', 'CX', 'CXR', 162),
  ('Cocos (Keeling) Islands', 'CC', 'CCK', 166),
  ('Colombia', 'CO', 'COL', 170),
  ('Comoros', 'KM', 'COM', 174),
  ('Congo', 'CG', 'COG', 178),
  ('Congo, the Democratic Republic of the', 'CD', 'COD', 180),
  ('Cook Islands', 'CK', 'COK', 184),
  ('Costa Rica', 'CR', 'CRI', 188),
  ('Côte d''Ivoire', 'CI', 'CIV', 384),
  ('Croatia', 'HR', 'HRV', 191),
  ('Cuba', 'CU', 'CUB', 192),
  ('Curaçao', 'CW', 'CUW', 531),
  ('Cyprus', 'CY', 'CYP', 196),
  ('Czech Republic', 'CZ', 'CZE', 203),
  ('Denmark', 'DK', 'DNK', 208),
  ('Djibouti', 'DJ', 'DJI', 262),
  ('Dominica', 'DM', 'DMA', 212),
  ('Dominican Republic', 'DO', 'DOM', 214),
  ('Ecuador', 'EC', 'ECU', 218),
  ('Egypt', 'EG', 'EGY', 818),
  ('El Salvador', 'SV', 'SLV', 222),
  ('Equatorial Guinea', 'GQ', 'GNQ', 226),
  ('Eritrea', 'ER', 'ERI', 232),
  ('Estonia', 'EE', 'EST', 233),
  ('Eswatini', 'SZ', 'SWZ', 748),
  ('Ethiopia', 'ET', 'ETH', 231),
  ('Falkland Islands (Malvinas)', 'FK', 'FLK', 238),
  ('Faroe Islands', 'FO', 'FRO', 234),
  ('Fiji', 'FJ', 'FJI', 242),
  ('Finland', 'FI', 'FIN', 246),
  ('France', 'FR', 'FRA', 250),
  ('French Guiana', 'GF', 'GUF', 254),
  ('French Polynesia', 'PF', 'PYF', 258),
  ('French Southern Territories', 'TF', 'ATF', 260),
  ('Gabon', 'GA', 'GAB', 266),
  ('Gambia', 'GM', 'GMB', 270),
  ('Georgia', 'GE', 'GEO', 268),
  ('Germany', 'DE', 'DEU', 276),
  ('Ghana', 'GH', 'GHA', 288),
  ('Gibraltar', 'GI', 'GIB', 292),
  ('Greece', 'GR', 'GRC', 300),
  ('Greenland', 'GL', 'GRL', 304),
  ('Grenada', 'GD', 'GRD', 308),
  ('Guadeloupe', 'GP', 'GLP', 312),
  ('Guam', 'GU', 'GUM', 316),
  ('Guatemala', 'GT', 'GTM', 320),
  ('Guernsey', 'GG', 'GGY', 831),
  ('Guinea', 'GN', 'GIN', 324),
  ('Guinea-Bissau', 'GW', 'GNB', 624),
  ('Guyana', 'GY', 'GUY', 328),
  ('Haiti', 'HT', 'HTI', 332),
  ('Heard Island and McDonald Islands', 'HM', 'HMD', 334),
  ('Holy See', 'VA', 'VAT', 336),
  ('Honduras', 'HN', 'HND', 340),
  ('Hong Kong', 'HK', 'HKG', 344),
  ('Hungary', 'HU', 'HUN', 348),
  ('Iceland', 'IS', 'ISL', 352),
  ('India', 'IN', 'IND', 356),
  ('Indonesia', 'ID', 'IDN', 360),
  ('Iran, Islamic Republic of', 'IR', 'IRN', 364),
  ('Iraq', 'IQ', 'IRQ', 368),
  ('Ireland', 'IE', 'IRL', 372),
  ('Isle of Man', 'IM', 'IMN', 833),
  ('Israel', 'IL', 'ISR', 376),
  ('Italy', 'IT', 'ITA', 380),
  ('Jamaica', 'JM', 'JAM', 388),
  ('Japan', 'JP', 'JPN', 392),
  ('Jersey', 'JE', 'JEY', 832),
  ('Jordan', 'JO', 'JOR', 400),
  ('Kazakhstan', 'KZ', 'KAZ', 398),
  ('Kenya', 'KE', 'KEN', 404),
  ('Kiribati', 'KI', 'KIR', 296),
  ('Korea, Democratic People''s Republic of', 'KP', 'PRK', 408),
  ('Korea, Republic of', 'KR', 'KOR', 410),
  ('Kuwait', 'KW', 'KWT', 414),
  ('Kyrgyzstan', 'KG', 'KGZ', 417),
  ('Lao People''s Democratic Republic', 'LA', 'LAO', 418),
  ('Latvia', 'LV', 'LVA', 428),
  ('Lebanon', 'LB', 'LBN', 422),
  ('Lesotho', 'LS', 'LSO', 426),
  ('Liberia', 'LR', 'LBR', 430),
  ('Libya', 'LY', 'LBY', 434),
  ('Liechtenstein', 'LI', 'LIE', 438),
  ('Lithuania', 'LT', 'LTU', 440),
  ('Luxembourg', 'LU', 'LUX', 442),
  ('Macao', 'MO', 'MAC', 446),
  ('Madagascar', 'MG', 'MDG', 450),
  ('Malawi', 'MW', 'MWI', 454),
  ('Malaysia', 'MY', 'MYS', 458),
  ('Maldives', 'MV', 'MDV', 462),
  ('Mali', 'ML', 'MLI', 466),
  ('Malta', 'MT', 'MLT', 470),
  ('Marshall Islands', 'MH', 'MHL', 584),
  ('Martinique', 'MQ', 'MTQ', 474),
  ('Mauritania', 'MR', 'MRT', 478),
  ('Mauritius', 'MU', 'MUS', 480),
  ('Mayotte', 'YT', 'MYT', 175),
  ('Mexico', 'MX', 'MEX', 484),
  ('Micronesia, Federated States of', 'FM', 'FSM', 583),
  ('Moldova, Republic of', 'MD', 'MDA', 498),
  ('Monaco', 'MC', 'MCO', 492),
  ('Mongolia', 'MN', 'MNG', 496),
  ('Montenegro', 'ME', 'MNE', 499),
  ('Montserrat', 'MS', 'MSR', 500),
  ('Morocco', 'MA', 'MAR', 504),
  ('Mozambique', 'MZ', 'MOZ', 508),
  ('Myanmar', 'MM', 'MMR', 104),
  ('Namibia', 'NA', 'NAM', 516),
  ('Nauru', 'NR', 'NRU', 520),
  ('Nepal', 'NP', 'NPL', 524),
  ('Netherlands', 'NL', 'NLD', 528),
  ('New Caledonia', 'NC', 'NCL', 540),
  ('New Zealand', 'NZ', 'NZL', 554),
  ('Nicaragua', 'NI', 'NIC', 558),
  ('Niger', 'NE', 'NER', 562),
  ('Nigeria', 'NG', 'NGA', 566),
  ('Niue', 'NU', 'NIU', 570),
  ('Norfolk Island', 'NF', 'NFK', 574),
  ('Northern Mariana Islands', 'MP', 'MNP', 580),
  ('Norway', 'NO', 'NOR', 578),
  ('Oman', 'OM', 'OMN', 512),
  ('Pakistan', 'PK', 'PAK', 586),
  ('Palau', 'PW', 'PLW', 585),
  ('Palestine, State of', 'PS', 'PSE', 275),
  ('Panama', 'PA', 'PAN', 591),
  ('Papua New Guinea', 'PG', 'PNG', 598),
  ('Paraguay', 'PY', 'PRY', 600),
  ('Peru', 'PE', 'PER', 604),
  ('Philippines', 'PH', 'PHL', 608),
  ('Pitcairn', 'PN', 'PCN', 612),
  ('Poland', 'PL', 'POL', 616),
  ('Portugal', 'PT', 'PRT', 620),
  ('Puerto Rico', 'PR', 'PRI', 630),
  ('Qatar', 'QA', 'QAT', 634),
  ('Réunion', 'RE', 'REU', 638),
  ('Romania', 'RO', 'ROU', 642),
  ('Russian Federation', 'RU', 'RUS', 643),
  ('Rwanda', 'RW', 'RWA', 646),
  ('Saint Barthélemy', 'BL', 'BLM', 652),
  ('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', 654),
  ('Saint Kitts and Nevis', 'KN', 'KNA', 659),
  ('Saint Lucia', 'LC', 'LCA', 662),
  ('Saint Martin (French part)', 'MF', 'MAF', 663),
  ('Saint Pierre and Miquelon', 'PM', 'SPM', 666),
  ('Saint Vincent and the Grenadines', 'VC', 'VCT', 670),
  ('Samoa', 'WS', 'WSM', 882),
  ('San Marino', 'SM', 'SMR', 674),
  ('Sao Tome and Principe', 'ST', 'STP', 678),
  ('Saudi Arabia', 'SA', 'SAU', 682),
  ('Senegal', 'SN', 'SEN', 686),
  ('Serbia', 'RS', 'SRB', 688),
  ('Seychelles', 'SC', 'SYC', 690),
  ('Sierra Leone', 'SL', 'SLE', 694),
  ('Singapore', 'SG', 'SGP', 702),
  ('Sint Maarten (Dutch part)', 'SX', 'SXM', 534),
  ('Slovakia', 'SK', 'SVK', 703),
  ('Slovenia', 'SI', 'SVN', 705),
  ('Solomon Islands', 'SB', 'SLB', 90),
  ('Somalia', 'SO', 'SOM', 706),
  ('South Africa', 'ZA', 'ZAF', 710),
  ('South Georgia and the South Sandwich Islands', 'GS', 'SGS', 239),
  ('South Sudan', 'SS', 'SSD', 728),
  ('Spain', 'ES', 'ESP', 724),
  ('Sri Lanka', 'LK', 'LKA', 144),
  ('Sudan', 'SD', 'SDN', 729),
  ('Suriname', 'SR', 'SUR', 740),
  ('Svalbard and Jan Mayen', 'SJ', 'SJM', 744),
  ('Sweden', 'SE', 'SWE', 752),
  ('Switzerland', 'CH', 'CHE', 756),
  ('Syrian Arab Republic', 'SY', 'SYR', 760),
  ('Taiwan, Province of China', 'TW', 'TWN', 158),
  ('Tajikistan', 'TJ', 'TJK', 762),
  ('Tanzania, United Republic of', 'TZ', 'TZA', 834),
  ('Thailand', 'TH', 'THA', 764),
  ('Timor-Leste', 'TL', 'TLS', 626),
  ('Togo', 'TG', 'TGO', 768),
  ('Tokelau', 'TK', 'TKL', 772),
  ('Tonga', 'TO', 'TON', 776),
  ('Trinidad and Tobago', 'TT', 'TTO', 780),
  ('Tunisia', 'TN', 'TUN', 788),
  ('Turkey', 'TR', 'TUR', 792),
  ('Turkmenistan', 'TM', 'TKM', 795),
  ('Turks and Caicos Islands', 'TC', 'TCA', 796),
  ('Tuvalu', 'TV', 'TUV', 798),
  ('Uganda', 'UG', 'UGA', 800),
  ('Ukraine', 'UA', 'UKR', 804),
  ('United Arab Emirates', 'AE', 'ARE', 784),
  ('United Kingdom of Great Britain and Northern Ireland', 'GB', 'GBR', 826),
  ('United States of America', 'US', 'USA', 840),
  ('Uruguay', 'UY', 'URY', 858),
  ('Uzbekistan', 'UZ', 'UZB', 860),
  ('Vanuatu', 'VU', 'VUT', 548),
  ('Venezuela, Bolivarian Republic of', 'VE', 'VEN', 862),
  ('Viet Nam', 'VN', 'VNM', 704),
  ('Virgin Islands (British)', 'VG', 'VGB', 92),
  ('Virgin Islands (U.S.)', 'VI', 'VIR', 850),
  ('Wallis and Futuna', 'WF', 'WLF', 876),
  ('Western Sahara', 'EH', 'ESH', 732),
  ('Yemen', 'YE', 'YEM', 887),
  ('Zambia', 'ZM', 'ZMB', 894),
  ('Zimbabwe', 'ZW', 'ZWE', 716);
--
-- Currency default data
--
insert into currency(
    name, code, num_code, symbol
) values
  ('United Arab Emirates Dirham', 'AED', 784, 'د.إ'),
  ('Afghan Afghani', 'AFN', 971, '؋'),
  ('Albanian Lek', 'ALL', 8, 'L'),
  ('Armenian Dram', 'AMD', 51, '֏'),
  ('Netherlands Antillean Guilder', 'ANG', 532, 'ƒ'),
  ('Angolan Kwanza', 'AOA', 973, 'Kz'),
  ('Argentine Peso', 'ARS', 32, '$'),
  ('Australian Dollar', 'AUD', 36, '$'),
  ('Aruban Florin', 'AWG', 533, 'ƒ'),
  ('Azerbaijani Manat', 'AZN', 944, '₼'),
  ('Bosnia and Herzegovina Convertible Mark', 'BAM', 977, 'KM'),
  ('Barbadian Dollar', 'BBD', 52, '$'),
  ('Bangladeshi Taka', 'BDT', 50, '৳'),
  ('Bulgarian Lev', 'BGN', 975, 'лв'),
  ('Bahraini Dinar', 'BHD', 48, '.د.ب'),
  ('Burundian Franc', 'BIF', 108, 'FBu'),
  ('Bermudian Dollar', 'BMD', 60, '$'),
  ('Brunei Dollar', 'BND', 96, '$'),
  ('Bolivian Boliviano', 'BOB', 68, 'Bs.'),
  ('Brazilian Real', 'BRL', 986, 'R$'),
  ('Bahamian Dollar', 'BSD', 44, '$'),
  ('Bhutanese Ngultrum', 'BTN', 64, 'Nu.'),
  ('Botswanan Pula', 'BWP', 72, 'P'),
  ('Belarusian Ruble', 'BYN', 933, 'Br'),
  ('Belize Dollar', 'BZD', 84, '$'),
  ('Canadian Dollar', 'CAD', 124, '$'),
  ('Congolese Franc', 'CDF', 976, 'FC'),
  ('Swiss Franc', 'CHF', 756, 'Fr'),
  ('Chilean Peso', 'CLP', 152, '$'),
  ('Chinese Yuan', 'CNY', 156, '¥'),
  ('Colombian Peso', 'COP', 170, '$'),
  ('Costa Rican Colón', 'CRC', 188, '₡'),
  ('Cuban Convertible Peso', 'CUC', 931, '$'),
  ('Cuban Peso', 'CUP', 192, '$'),
  ('Cape Verdean Escudo', 'CVE', 132, 'Esc'),
  ('Czech Koruna', 'CZK', 203, 'Kč'),
  ('Djiboutian Franc', 'DJF', 262, 'Fdj'),
  ('Danish Krone', 'DKK', 208, 'kr'),
  ('Dominican Peso', 'DOP', 214, 'RD$'),
  ('Algerian Dinar', 'DZD', 12, 'دج'),
  ('Egyptian Pound', 'EGP', 818, 'E£'),
  ('Eritrean Nakfa', 'ERN', 232, 'Nfk'),
  ('Ethiopian Birr', 'ETB', 230, 'Br'),
  ('Euro', 'EUR', 978, '€'),
  ('Fijian Dollar', 'FJD', 242, '$'),
  ('Falkland Islands Pound', 'FKP', 238, '£'),
  ('British Pound Sterling', 'GBP', 826, '£'),
  ('Georgian Lari', 'GEL', 981, '₾'),
  ('Ghanaian Cedi', 'GHS', 936, '₵'),
  ('Gibraltar Pound', 'GIP', 292, '£'),
  ('Gambian Dalasi', 'GMD', 270, 'D'),
  ('Guinean Franc', 'GNF', 324, 'FG'),
  ('Guatemalan Quetzal', 'GTQ', 320, 'Q'),
  ('Guyanaese Dollar', 'GYD', 328, '$'),
  ('Hong Kong Dollar', 'HKD', 344, '$'),
  ('Honduran Lempira', 'HNL', 340, 'L'),
  ('Croatian Kuna', 'HRK', 191, 'kn'),
  ('Haitian Gourde', 'HTG', 332, 'G'),
  ('Hungarian Forint', 'HUF', 348, 'Ft'),
  ('Indonesian Rupiah', 'IDR', 360, 'Rp'),
  ('Israeli New Shekel', 'ILS', 376, '₪'),
  ('Indian Rupee', 'INR', 356, '₹'),
  ('Iraqi Dinar', 'IQD', 368, 'ع.د'),
  ('Iranian Rial', 'IRR', 364, '﷼'),
  ('Icelandic Króna', 'ISK', 352, 'kr'),
  ('Jamaican Dollar', 'JMD', 388, 'J$'),
  ('Jordanian Dinar', 'JOD', 400, 'JD'),
  ('Japanese Yen', 'JPY', 392, '¥'),
  ('Kenyan Shilling', 'KES', 404, 'KSh'),
  ('Kyrgyzstani Som', 'KGS', 417, 'с'),
  ('Cambodian Riel', 'KHR', 116, '៛'),
  ('Comorian Franc', 'KMF', 174, 'CF'),
  ('North Korean Won', 'KPW', 408, '₩'),
  ('South Korean Won', 'KRW', 410, '₩'),
  ('Kuwaiti Dinar', 'KWD', 414, 'د.ك'),
  ('Cayman Islands Dollar', 'KYD', 136, '$'),
  ('Kazakhstani Tenge', 'KZT', 398, '₸'),
  ('Lao Kip', 'LAK', 418, '₭'),
  ('Lebanese Pound', 'LBP', 422, 'ل.ل'),
  ('Sri Lankan Rupee', 'LKR', 144, 'Rs'),
  ('Liberian Dollar', 'LRD', 430, '$'),
  ('Lesotho Loti', 'LSL', 426, 'L'),
  ('Libyan Dinar', 'LYD', 434, 'LD'),
  ('Moroccan Dirham', 'MAD', 504, 'MAD'),
  ('Moldovan Leu', 'MDL', 498, 'L'),
  ('Malagasy Ariary', 'MGA', 969, 'Ar'),
  ('Macedonian Denar', 'MKD', 807, 'ден'),
  ('Myanmar Kyat', 'MMK', 104, 'K'),
  ('Mongolian Tögrög', 'MNT', 496, '₮'),
  ('Macanese Pataca', 'MOP', 446, 'MOP$'),
  ('Mauritanian Ouguiya', 'MRU', 929, 'UM'),
  ('Mauritian Rupee', 'MUR', 480, 'Rs'),
  ('Maldivian Rufiyaa', 'MVR', 462, 'Rf'),
  ('Malawian Kwacha', 'MWK', 454, 'MK'),
  ('Mexican Peso', 'MXN', 484, '$'),
  ('Malaysian Ringgit', 'MYR', 458, 'RM'),
  ('Mozambican Metical', 'MZN', 943, 'MT'),
  ('Namibian Dollar', 'NAD', 516, '$'),
  ('Nigerian Naira', 'NGN', 566, '₦'),
  ('Nicaraguan Córdoba', 'NIO', 558, 'C$'),
  ('Norwegian Krone', 'NOK', 578, 'kr'),
  ('Nepalese Rupee', 'NPR', 524, '₨'),
  ('New Zealand Dollar', 'NZD', 554, '$'),
  ('Omani Rial', 'OMR', 512, '﷼'),
  ('Panamanian Balboa', 'PAB', 590, 'B/.'),
  ('Peruvian Sol', 'PEN', 604, 'S/.'),
  ('Papua New Guinean Kina', 'PGK', 598, 'K'),
  ('Philippine Peso', 'PHP', 608, '₱'),
  ('Pakistani Rupee', 'PKR', 586, 'Rs'),
  ('Polish Zloty', 'PLN', 985, 'zł'),
  ('Paraguayan Guarani', 'PYG', 600, '₲'),
  ('Qatari Riyal', 'QAR', 634, '﷼'),
  ('Romanian Leu', 'RON', 946, 'lei'),
  ('Serbian Dinar', 'RSD', 941, 'дин.'),
  ('Russian Ruble', 'RUB', 643, '₽'),
  ('Rwandan Franc', 'RWF', 646, 'FRw'),
  ('Saudi Riyal', 'SAR', 682, '﷼'),
  ('Solomon Islands Dollar', 'SBD', 90, '$'),
  ('Seychellois Rupee', 'SCR', 690, '₨'),
  ('Sudanese Pound', 'SDG', 938, 'ج.س.'),
  ('Swedish Krona', 'SEK', 752, 'kr'),
  ('Singapore Dollar', 'SGD', 702, '$'),
  ('Saint Helena Pound', 'SHP', 654, '£'),
  ('Sierra Leonean Leone', 'SLL', 694, 'Le'),
  ('Somali Shilling', 'SOS', 706, 'Sh'),
  ('Surinamese Dollar', 'SRD', 968, '$'),
  ('South Sudanese Pound', 'SSP', 728, '£'),
  ('São Tomé and Príncipe Dobra', 'STN', 930, 'Db'),
  ('Salvadoran Colón', 'SVC', 222, '₡'),
  ('Syrian Pound', 'SYP', 760, '£'),
  ('Eswatini Lilangeni', 'SZL', 748, 'E'),
  ('Thai Baht', 'THB', 764, '฿'),
  ('Tajikistani Somoni', 'TJS', 972, 'ЅМ'),
  ('Turkmenistan Manat', 'TMT', 934, 'm'),
  ('Tunisian Dinar', 'TND', 788, 'د.ت'),
  ('Tongan Paʻanga', 'TOP', 776, 'T$'),
  ('Turkish Lira', 'TRY', 949, '₺'),
  ('Trinidad and Tobago Dollar', 'TTD', 780, 'TT$'),
  ('New Taiwan Dollar', 'TWD', 901, 'NT$'),
  ('Tanzanian Shilling', 'TZS', 834, 'Sh'),
  ('Ukrainian Hryvnia', 'UAH', 980, '₴'),
  ('Ugandan Shilling', 'UGX', 800, 'USh'),
  ('United States Dollar', 'USD', 840, '$'),
  ('Uruguayan Peso', 'UYU', 858, '$'),
  ('Uzbekistan Som', 'UZS', 860, 'лв'),
  ('Venezuelan Bolívar Soberano', 'VES', 928, 'Bs.S'),
  ('Vietnamese Dong', 'VND', 704, '₫'),
  ('Vanuatu Vatu', 'VUV', 548, 'VT'),
  ('Samoan Tala', 'WST', 882, 'WS$'),
  ('CFA Franc BEAC', 'XAF', 950, 'FCFA'),
  ('East Caribbean Dollar', 'XCD', 951, '$'),
  ('CFA Franc BCEAO', 'XOF', 952, 'CFA'),
  ('CFP Franc', 'XPF', 953, '₣'),
  ('Yemeni Rial', 'YER', 886, '﷼'),
  ('South African Rand', 'ZAR', 710, 'R'),
  ('Zambian Kwacha', 'ZMW', 967, 'ZK'),
  ('Zimbabwean Dollar', 'ZWL', 932, '$');
--
-- Mapping country - currency data
--
do $$
declare
    rec           record;
    v_country_id  varchar(32);
    v_currency_id varchar(32);
begin
    for rec in
        select * from (values
            ('AF', 'AFN'),
            ('AX', 'EUR'),
            ('AL', 'ALL'),
            ('DZ', 'DZD'),
            ('AS', 'USD'),
            ('AD', 'EUR'),
            ('AO', 'AOA'),
            ('AI', 'XCD'),
            -- Antarctica ('AQ') is omitted due to lack of official currency.
            ('AG', 'XCD'),
            ('AR', 'ARS'),
            ('AM', 'AMD'),
            ('AW', 'AWG'),
            ('AU', 'AUD'),
            ('AT', 'EUR'),
            ('AZ', 'AZN'),
            ('BS', 'BSD'),
            ('BH', 'BHD'),
            ('BD', 'BDT'),
            ('BB', 'BBD'),
            ('BY', 'BYN'),
            ('BE', 'EUR'),
            ('BZ', 'BZD'),
            ('BJ', 'XOF'),
            ('BM', 'BMD'),
            ('BT', 'BTN'),
            ('BO', 'BOB'),
            ('BQ', 'USD'),
            ('BA', 'BAM'),
            ('BW', 'BWP'),
            ('BV', 'NOK'),
            ('BR', 'BRL'),
            ('IO', 'USD'),
            ('BN', 'BND'),
            ('BG', 'BGN'),
            ('BF', 'XOF'),
            ('BI', 'BIF'),
            ('CV', 'CVE'),
            ('KH', 'KHR'),
            ('CM', 'XAF'),
            ('CA', 'CAD'),
            ('KY', 'KYD'),
            ('CF', 'XAF'),
            ('TD', 'XAF'),
            ('CL', 'CLP'),
            ('CN', 'CNY'),
            ('CX', 'AUD'),
            ('CC', 'AUD'),
            ('CO', 'COP'),
            ('KM', 'KMF'),
            ('CG', 'XAF'),
            ('CD', 'CDF'),
            ('CK', 'NZD'),
            ('CR', 'CRC'),
            ('CI', 'XOF'),
            ('HR', 'HRK'),
            ('CU', 'CUP'),
            ('CW', 'ANG'),
            ('CY', 'EUR'),
            ('CZ', 'CZK'),
            ('DK', 'DKK'),
            ('DJ', 'DJF'),
            ('DM', 'XCD'),
            ('DO', 'DOP'),
            ('EC', 'USD'),
            ('EG', 'EGP'),
            ('SV', 'USD'),
            ('GQ', 'XAF'),
            ('ER', 'ERN'),
            ('EE', 'EUR'),
            ('SZ', 'SZL'),
            ('ET', 'ETB'),
            ('FK', 'FKP'),
            ('FO', 'DKK'),
            ('FJ', 'FJD'),
            ('FI', 'EUR'),
            ('FR', 'EUR'),
            ('GF', 'EUR'),
            ('PF', 'XPF'),
            ('TF', 'EUR'),
            ('GA', 'XAF'),
            ('GM', 'GMD'),
            ('GE', 'GEL'),
            ('DE', 'EUR'),
            ('GH', 'GHS'),
            ('GI', 'GIP'),
            ('GR', 'EUR'),
            ('GL', 'DKK'),
            ('GD', 'XCD'),
            ('GP', 'EUR'),
            ('GU', 'USD'),
            ('GT', 'GTQ'),
            ('GG', 'GBP'),
            ('GN', 'GNF'),
            ('GW', 'XOF'),
            ('GY', 'GYD'),
            ('HT', 'HTG'),
            ('HM', 'AUD'),
            ('VA', 'EUR'),
            ('HN', 'HNL'),
            ('HK', 'HKD'),
            ('HU', 'HUF'),
            ('IS', 'ISK'),
            ('IN', 'INR'),
            ('ID', 'IDR'),
            ('IR', 'IRR'),
            ('IQ', 'IQD'),
            ('IE', 'EUR'),
            ('IM', 'GBP'),
            ('IL', 'ILS'),
            ('IT', 'EUR'),
            ('JM', 'JMD'),
            ('JP', 'JPY'),
            ('JE', 'GBP'),
            ('JO', 'JOD'),
            ('KZ', 'KZT'),
            ('KE', 'KES'),
            ('KI', 'AUD'),
            ('KP', 'KPW'),
            ('KR', 'KRW'),
            ('KW', 'KWD'),
            ('KG', 'KGS'),
            ('LA', 'LAK'),
            ('LV', 'EUR'),
            ('LB', 'LBP'),
            ('LS', 'LSL'),
            ('LR', 'LRD'),
            ('LY', 'LYD'),
            ('LI', 'CHF'),
            ('LT', 'EUR'),
            ('LU', 'EUR'),
            ('MO', 'MOP'),
            ('MG', 'MGA'),
            ('MW', 'MWK'),
            ('MY', 'MYR'),
            ('MV', 'MVR'),
            ('ML', 'XOF'),
            ('MT', 'EUR'),
            ('MH', 'USD'),
            ('MQ', 'EUR'),
            ('MR', 'MRU'),
            ('MU', 'MUR'),
            ('YT', 'EUR'),
            ('MX', 'MXN'),
            ('FM', 'USD'),
            ('MD', 'MDL'),
            ('MC', 'EUR'),
            ('MN', 'MNT'),
            ('ME', 'EUR'),
            ('MS', 'XCD'),
            ('MA', 'MAD'),
            ('MZ', 'MZN'),
            ('MM', 'MMK'),
            ('NA', 'NAD'),
            ('NR', 'AUD'),
            ('NP', 'NPR'),
            ('NL', 'EUR'),
            ('NC', 'XPF'),
            ('NZ', 'NZD'),
            ('NI', 'NIO'),
            ('NE', 'XOF'),
            ('NG', 'NGN'),
            ('NU', 'NZD'),
            ('NF', 'AUD'),
            ('MP', 'USD'),
            ('NO', 'NOK'),
            ('OM', 'OMR'),
            ('PK', 'PKR'),
            ('PW', 'USD'),
            ('PS', 'ILS'),
            ('PA', 'USD'),
            ('PA', 'PAB'),
            ('PG', 'PGK'),
            ('PY', 'PYG'),
            ('PE', 'PEN'),
            ('PH', 'PHP'),
            ('PN', 'NZD'),
            ('PL', 'PLN'),
            ('PT', 'EUR'),
            ('PR', 'USD'),
            ('QA', 'QAR'),
            ('RE', 'EUR'),
            ('RO', 'RON'),
            ('RU', 'RUB'),
            ('RW', 'RWF'),
            ('BL', 'EUR'),
            ('SH', 'SHP'),
            ('KN', 'XCD'),
            ('LC', 'XCD'),
            ('MF', 'EUR'),
            ('PM', 'EUR'),
            ('VC', 'XCD'),
            ('WS', 'WST'),
            ('SM', 'EUR'),
            ('ST', 'STN'),
            ('SA', 'SAR'),
            ('SN', 'XOF'),
            ('RS', 'RSD'),
            ('SC', 'SCR'),
            ('SL', 'SLL'),
            ('SG', 'SGD'),
            ('SX', 'ANG'),
            ('SK', 'EUR'),
            ('SI', 'EUR'),
            ('SB', 'SBD'),
            ('SO', 'SOS'),
            ('ZA', 'ZAR'),
            ('GS', 'GBP'),
            ('SS', 'SSP'),
            ('ES', 'EUR'),
            ('LK', 'LKR'),
            ('SD', 'SDG'),
            ('SR', 'SRD'),
            ('SJ', 'NOK'),
            ('SE', 'SEK'),
            ('CH', 'CHF'),
            ('SY', 'SYP'),
            ('TW', 'TWD'),
            ('TJ', 'TJS'),
            ('TZ', 'TZS'),
            ('TH', 'THB'),
            ('TL', 'USD'),
            ('TG', 'XOF'),
            ('TK', 'NZD'),
            ('TO', 'TOP'),
            ('TT', 'TTD'),
            ('TN', 'TND'),
            ('TR', 'TRY'),
            ('TM', 'TMT'),
            ('TC', 'USD'),
            ('TV', 'AUD'),
            ('UG', 'UGX'),
            ('UA', 'UAH'),
            ('AE', 'AED'),
            ('GB', 'GBP'),
            ('US', 'USD'),
            ('UY', 'UYU'),
            ('UZ', 'UZS'),
            ('VU', 'VUV'),
            ('VE', 'VES'),
            ('VN', 'VND'),
            ('VG', 'USD'),
            ('VI', 'USD'),
            ('WF', 'XPF'),
            ('EH', 'MAD'),
            ('YE', 'YER'),
            ('ZM', 'ZMW'),
            ('ZW', 'USD'),
            ('ZW', 'ZAR')
        ) as mapping(country_iso2, currency_code)
    loop
        select id into v_country_id from country where iso2 = rec.country_iso2;
        select id into v_currency_id from currency where code = rec.currency_code;
        
        insert into country_currency (country_id, currency_id)
            values (v_country_id, v_currency_id);
    end loop;
end;
$$;
--
-- eof
--
