apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: brickwall:0.1.0
          command: ["/app/bsp", "auth"]
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: auth-config
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  ports:
    - port: 8082
  selector:
    app: auth
