apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # Base64 encoded значение (например, "postgres")
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # Base64 encoded значение (например, "password")
